# Generated by Django 5.1.7 on 2025-03-12 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_teacher_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade_level',
        ),
    ]
