# Generated by Django 5.1.7 on 2025-03-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_student_grade_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='teacher',
            new_name='created_by',
        ),
    ]
