# Generated by Django 5.1.7 on 2025-03-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_assignment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='homework_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
